<?php

namespace Database\Seeders;

use App\Models\SblContact;
use Illuminate\Database\Seeder;

class SblContactSeeder extends Seeder
{
    public function run(): void
    {
        $contacts = [
            [
                'id' => 1,
                'department' => 'Customer Care & Support Cell',
                'contact_person' => 'Support Team',
                'department_en' => 'Customer Care & Support Cell',
                'department_bn' => 'কাস্টমার কেয়ার ও সাপোর্ট সেল',
                'service_label_en' => '24/7 Helpline',
                'service_label_bn' => '২৪/৭ হেল্পলাইন',
                'badge' => '24/7 Helpline',
                'contact_person' => 'সাপোর্ট টিম',
                'phone' => '01700000000',
                'whatsapp' => '01700000000',
                'email' => 'support@sbl.com.bd',
                'available_hours' => '24/7 Support (Always Available)',
                'hours_en' => '24/7 Support (Always Available)',
                'hours_bn' => '২৪/৭ সাপোর্ট (সার্বক্ষণিক)',
                'description' => 'Contact for general inquiries, service-related questions, and immediate assistance.',
                'description_en' => 'Contact for general inquiries, service-related questions, and immediate assistance.',
                'description_bn' => 'যেকোনো সাধারণ তথ্য, সার্ভিস সংক্রান্ত প্রশ্ন ও তাত্ক্ষণিক অনুসন্ধানের জন্য যোগাযোগ করুন।',
                'icon' => '📞',
                'badge' => '24/7 Helpline',
                'category' => 'customer_care',
                'priority' => 1,
                'is_primary' => true,
                'is_24_hours' => true,
                'verification_status' => 'needs_review',
                'is_official' => false,
                'is_active' => true,
                'is_public' => true,
                'sort_order' => 1,
                'days' => 'Daily',
                'open_time' => '00:00',
                'close_time' => '23:59',
            ],
            [
                'id' => 2,
                'department' => 'Dropshipping & Merchant Desk',
                'contact_person' => 'Merchant Support Officer',
                'department_en' => 'Dropshipping & Merchant Desk',
                'department_bn' => 'ড্রপশিপিং ও মার্চেন্ট ডেস্ক',
                'service_label_en' => 'Dropship Support',
                'service_label_bn' => 'ড্রপশিপিং সাপোর্ট',
                'badge' => 'Dropship Support',
                'contact_person' => 'মার্চেন্ট সাপোর্ট অফিসার',
                'phone' => '01800000001',
                'whatsapp' => '01800000001',
                'email' => 'dropship@sbl.com.bd',
                'available_hours' => '10:00 AM - 08:00 PM',
                'hours_en' => '10:00 AM - 08:00 PM',
                'hours_bn' => 'সকাল ১০:০০ - রাত ০৮:০০',
                'description' => 'Support for dropshipping inventory, order fulfillment, courier delivery status, and merchant onboarding.',
                'description_en' => 'Support for dropshipping inventory, order fulfillment, courier delivery status, and merchant onboarding.',
                'description_bn' => 'ড্রপশিপিং পণ্য স্টক, অর্ডার প্রসেসিং, কুরিয়ার স্ট্যাটাস ও মার্চেন্ট সংক্রান্ত সমস্যার সমাধান।',
                'icon' => '🛍️',
                'badge' => 'Dropship Support',
                'category' => 'dropshipping',
                'priority' => 2,
                'is_primary' => false,
                'is_24_hours' => false,
                'open_time' => '10:00',
                'close_time' => '20:00',
                'days' => 'Sat - Thu',
                'verification_status' => 'needs_review',
                'is_official' => false,
                'is_active' => true,
                'is_public' => true,
                'sort_order' => 2,
            ],
            [
                'id' => 3,
                'department' => 'Investor & Crowdfunding Cell',
                'contact_person' => 'Investment Relations Officer',
                'department_en' => 'Investor & Crowdfunding Cell',
                'department_bn' => 'ইনভেস্টর ও ক্রাউডফান্ডিং সেল',
                'service_label_en' => 'Investor Hotline',
                'service_label_bn' => 'ইনভেস্টর হটলাইন',
                'badge' => 'Investor Hotline',
                'contact_person' => 'ইনভেস্টমেন্ট রিলেশন অফিসার',
                'phone' => '01900000002',
                'whatsapp' => '01900000002',
                'email' => 'invest@sbl.com.bd',
                'available_hours' => '10:00 AM - 08:00 PM',
                'hours_en' => '10:00 AM - 08:00 PM',
                'hours_bn' => 'সকাল ১০:০০ - রাত ০৮:০০',
                'description' => 'Information on 120,000/- & 550,000/- BDT crowdfunding packages and weekly profit-sharing plans.',
                'description_en' => 'Information on 120,000/- & 550,000/- BDT crowdfunding packages and weekly profit-sharing plans.',
                'description_bn' => '১২০,০০০/- ও ৫৫০,০০০/- টাকার ক্রাউডফান্ডিং প্যাকেজ ও সাপ্তাহিক প্রফিট শেয়ারিং সংক্রান্ত তথ্য।',
                'icon' => '📈',
                'badge' => 'Investor Hotline',
                'category' => 'business',
                'priority' => 3,
                'is_primary' => false,
                'is_24_hours' => false,
                'open_time' => '10:00',
                'close_time' => '20:00',
                'days' => 'Sat - Thu',
                'verification_status' => 'needs_review',
                'is_official' => false,
                'is_active' => true,
                'is_public' => true,
                'sort_order' => 3,
            ],
            [
                'id' => 4,
                'department' => 'IT & Member Portal Support',
                'contact_person' => 'System Admin',
                'department_en' => 'IT & Member Portal Support',
                'department_bn' => 'আইটি ও মেম্বার পোর্টাল সাপোর্ট',
                'service_label_en' => 'IT Team',
                'service_label_bn' => 'আইটি টিম',
                'badge' => 'IT Team',
                'contact_person' => 'সিস্টেম অ্যাডমিন',
                'phone' => '01600000003',
                'whatsapp' => '01600000003',
                'email' => 'tech@sbl.com.bd',
                'available_hours' => '10:00 AM - 10:00 PM',
                'hours_en' => '10:00 AM - 10:00 PM',
                'hours_bn' => 'সকাল ১০:০০ - রাত ১০:০০',
                'description' => 'Assistance with portal login issues, back-office dashboard errors, and technical queries.',
                'description_en' => 'Assistance with portal login issues, back-office dashboard errors, and technical queries.',
                'description_bn' => 'অ্যাপ লগইন সমস্যা, ব্যাকঅফিস ড্যাশবোর্ড বা টেকনিক্যাল সহযোগিতার জন্য।',
                'icon' => '💻',
                'badge' => 'IT Team',
                'is_primary' => false,
                'category' => 'technical',
                'priority' => 4,
                'is_primary' => true,
                'is_24_hours' => false,
                'open_time' => '10:00',
                'close_time' => '22:00',
                'days' => 'Daily',
                'verification_status' => 'needs_review',
                'is_official' => false,
                'is_active' => true,
                'is_public' => true,
                'sort_order' => 4,
            ],
            [
                'id' => 5,
                'department' => 'Counseling & Leadership Training',
                'contact_person' => 'Training Coordinator',
                'department_en' => 'Counseling & Leadership Training',
                'department_bn' => 'কাউন্সেলিং ও লিডারশিপ ট্রেনিং',
                'service_label_en' => 'Training Desk',
                'service_label_bn' => 'ট্রেনিং ডেস্ক',
                'badge' => 'Training Desk',
                'contact_person' => 'ট্রেনিং কো-অর্ডিনেটর',
                'phone' => '01500000004',
                'whatsapp' => '01500000004',
                'email' => 'training@sbl.com.bd',
                'available_hours' => '10:00 AM - 07:00 PM',
                'hours_en' => '10:00 AM - 07:00 PM',
                'hours_bn' => 'সকাল ১০:০০ - সন্ধ্যা ০৭:০০',
                'description' => 'Schedule and book Counseling-1 guidance and leadership workshop sessions.',
                'description_en' => 'Schedule and book Counseling-1 guidance and leadership workshop sessions.',
                'description_bn' => 'কাউন্সেলিং-১ এবং লিডারশিপ ট্রেইনিং সেশন বুকিং ও শিডিউল নিশ্চিতকরণ।',
                'icon' => '🎓',
                'badge' => 'Training Desk',
                'category' => 'training',
                'priority' => 5,
                'is_primary' => false,
                'is_24_hours' => false,
                'open_time' => '10:00',
                'close_time' => '19:00',
                'days' => 'Sat - Thu',
                'verification_status' => 'needs_review',
                'is_official' => false,
                'is_active' => true,
                'is_public' => true,
                'sort_order' => 5,
            ],
            [
                'id' => 6,
                'department' => 'Accounts & Commission Payout Desk',
                'contact_person' => 'Finance Executive',
                'department_en' => 'Accounts & Commission Payout Desk',
                'department_bn' => 'অ্যাকাউন্টস ও কমিশন পে-আউট ডেস্ক',
                'service_label_en' => 'Finance Desk',
                'service_label_bn' => 'ফাইন্যান্স ডেস্ক',
                'badge' => 'Finance Desk',
                'contact_person' => 'ফাইন্যান্স এক্সিকিউটিভ',
                'phone' => '01700000005',
                'whatsapp' => '01700000005',
                'email' => 'accounts@sbl.com.bd',
                'available_hours' => '11:00 AM - 06:00 PM (Sun-Thu)',
                'hours_en' => '11:00 AM - 06:00 PM (Sun-Thu)',
                'hours_bn' => 'বেলা ১১:০০ - বিকাল ০৬:০০ (রবি-বৃহস্পতি)',
                'description' => 'Inquiries regarding wallet withdrawals, referral commission statements, and payouts.',
                'description_en' => 'Inquiries regarding wallet withdrawals, referral commission statements, and payouts.',
                'description_bn' => 'উইথড্রয়াল, রেফারেল কমিশন স্টেটমেন্ট ও ফাইন্যান্সিয়াল ট্রানজ্যাকশন সংক্রান্ত যোগাযোগ।',
                'icon' => '💳',
                'badge' => 'Finance Desk',
                'is_primary' => false,
                'category' => 'accounts',
                'priority' => 6,
                'is_primary' => true,
                'is_24_hours' => false,
                'open_time' => '11:00',
                'close_time' => '18:00',
                'days' => 'Sun - Thu',
                'verification_status' => 'needs_review',
                'is_official' => false,
                'is_active' => true,
                'is_public' => true,
                'sort_order' => 6,
            ],
        ];

        // Clean up duplicate records if id > 6
        SblContact::where('id', '>', 6)->delete();

        foreach ($contacts as $contact) {
            SblContact::updateOrCreate(
                ['id' => $contact['id']],
                $contact
            );
        }
    }
}
