<?php

return [
    // --- Category: Dropshipping & E-Commerce Core ---
    [
        'code' => 'SBL',
        'name' => 'Smart Business Link',
        'category' => 'E-Commerce Core',
        'category_slug' => 'ecommerce',
        'meaning_bn' => 'SBL E-Commerce & Dropshipping Ecosystem',
        'description_bn' => 'SBL is a comprehensive business platform operating dropshipping, merchant networks, and member back-offices.',
        'icon' => '🌐',
        'tag' => 'Ecosystem',
    ],
    [
        'code' => 'COD',
        'name' => 'Cash On Delivery',
        'category' => 'E-Commerce Core',
        'category_slug' => 'ecommerce',
        'meaning_bn' => 'Payment delivery model where payment is made upon receipt',
        'description_bn' => 'The customer pays the full parcel amount to the delivery rider upon receiving the product. Approx 90% of local e-commerce sales use COD.',
        'icon' => '💵',
        'tag' => 'Payment',
    ],
    [
        'code' => 'SKU',
        'name' => 'Stock Keeping Unit',
        'category' => 'E-Commerce Core',
        'category_slug' => 'ecommerce',
        'meaning_bn' => 'Unique product identification code',
        'description_bn' => 'Unique alphanumeric code used in inventory management to track distinct product variants like size, color, or model.',
        'icon' => '🏷️',
        'tag' => 'Inventory',
    ],
    [
        'code' => 'AOV',
        'name' => 'Average Order Value',
        'category' => 'E-Commerce Core',
        'category_slug' => 'ecommerce',
        'meaning_bn' => 'Average Order Value',
        'description_bn' => 'Calculated by dividing total sales revenue by total number of orders (Total Revenue / Total Orders).',
        'icon' => '📊',
        'tag' => 'Revenue',
    ],
    [
        'code' => 'MOQ',
        'name' => 'Minimum Order Quantity',
        'category' => 'E-Commerce Core',
        'category_slug' => 'ecommerce',
        'meaning_bn' => 'Minimum Order Quantity',
        'description_bn' => 'The lowest quantity of units a supplier requires for purchase. Dropshipping typically eliminates MOQ restrictions.',
        'icon' => '📦',
        'tag' => 'Sourcing',
    ],
    [
        'code' => 'B2B',
        'name' => 'Business to Business',
        'category' => 'E-Commerce Core',
        'category_slug' => 'ecommerce',
        'meaning_bn' => 'Business to Business transactions',
        'description_bn' => 'Commercial transactions where suppliers or manufacturers sell goods directly to dropshippers, merchants, or wholesalers.',
        'icon' => '🏢',
        'tag' => 'Model',
    ],
    [
        'code' => 'B2C',
        'name' => 'Business to Consumer',
        'category' => 'E-Commerce Core',
        'category_slug' => 'ecommerce',
        'meaning_bn' => 'Direct sales from business to retail consumers',
        'description_bn' => 'Sales model where dropshippers sell goods directly to individual end-users via social media or e-commerce websites.',
        'icon' => '🛍️',
        'tag' => 'Model',
    ],
    [
        'code' => 'D2C',
        'name' => 'Direct to Consumer',
        'category' => 'E-Commerce Core',
        'category_slug' => 'ecommerce',
        'meaning_bn' => 'Direct to Consumer brand model without intermediaries',
        'description_bn' => 'Selling brand products directly to consumers through an owned website or sales funnel without third-party marketplace dependence.',
        'icon' => '🎯',
        'tag' => 'Brand',
    ],
    [
        'code' => 'MR',
        'name' => 'Merchant Reseller',
        'category' => 'E-Commerce Core',
        'category_slug' => 'ecommerce',
        'meaning_bn' => 'Merchant Reseller or dropship partner',
        'description_bn' => 'Registered partner on the SBL platform marketing products without holding physical inventory to earn profit margins.',
        'icon' => '🤝',
        'tag' => 'Partner',
    ],

    // --- Category: Logistics & Delivery ---
    [
        'code' => 'RTO',
        'name' => 'Return To Origin',
        'category' => 'Logistics & Delivery',
        'category_slug' => 'logistics',
        'meaning_bn' => 'Return to Origin when parcel delivery fails',
        'description_bn' => 'If a customer refuses delivery or cannot be reached, the courier returns the parcel to the warehouse. Reducing RTO is vital for profitability.',
        'icon' => '🔄',
        'tag' => 'Courier',
    ],
    [
        'code' => 'NDR',
        'name' => 'Non-Delivery Report',
        'category' => 'Logistics & Delivery',
        'category_slug' => 'logistics',
        'meaning_bn' => 'Non-Delivery Report with failed delivery reasons',
        'description_bn' => 'Report raised on courier portals when a rider fails delivery or the customer requests delivery postponement.',
        'icon' => '⚠️',
        'tag' => 'Courier',
    ],
    [
        'code' => 'AWB',
        'name' => 'Air Waybill / Consignment Tracking Number',
        'category' => 'Logistics & Delivery',
        'category_slug' => 'logistics',
        'meaning_bn' => 'Air Waybill / Consignment Tracking Number',
        'description_bn' => 'Unique barcode and number assigned to every parcel enabling real-time status and transit tracking by customers and merchants.',
        'icon' => '🚚',
        'tag' => 'Tracking',
    ],
    [
        'code' => '3PL',
        'name' => 'Third-Party Logistics',
        'category' => 'Logistics & Delivery',
        'category_slug' => 'logistics',
        'meaning_bn' => 'Third-Party Logistics service provider',
        'description_bn' => 'External logistics companies providing warehousing, packaging, and door-to-door delivery services (e.g. Steadfast, RedX, Paperfly).',
        'icon' => '📦',
        'tag' => 'Logistics',
    ],
    [
        'code' => 'TAT',
        'name' => 'Turnaround Time',
        'category' => 'Logistics & Delivery',
        'category_slug' => 'logistics',
        'meaning_bn' => 'Turnaround Time from order placement to final delivery',
        'description_bn' => 'Total turnaround duration measured in hours or days between order confirmation and successful doorstep delivery.',
        'icon' => '⏱️',
        'tag' => 'Speed',
    ],
    [
        'code' => 'SLA',
        'name' => 'Service Level Agreement',
        'category' => 'Logistics & Delivery',
        'category_slug' => 'logistics',
        'meaning_bn' => 'Service Level Agreement for logistics delivery timelines',
        'description_bn' => 'Contractual standard between merchants and couriers defining required pickup, transit, and delivery performance windows.',
        'icon' => '📝',
        'tag' => 'Standard',
    ],
    [
        'code' => 'POD',
        'name' => 'Proof of Delivery',
        'category' => 'Logistics & Delivery',
        'category_slug' => 'logistics',
        'meaning_bn' => 'Proof of Delivery confirmation',
        'description_bn' => 'Digital proof including customer signature, OTP verification, or parcel receipt confirmation upon delivery completion.',
        'icon' => '✅',
        'tag' => 'Delivery',
    ],

    // --- Category: Digital Marketing & Ads ---
    [
        'code' => 'ROAS',
        'name' => 'Return On Ad Spend',
        'category' => 'Marketing & Ads',
        'category_slug' => 'marketing',
        'meaning_bn' => 'Return On Ad Spend (Revenue ÷ Ad Spend)',
        'description_bn' => 'Marketing metric measuring revenue generated per currency unit spent on advertising (e.g., 20,000 revenue on 5,000 ad spend = 4X ROAS).',
        'icon' => '🎯',
        'tag' => 'Efficiency',
    ],
    [
        'code' => 'CPA',
        'name' => 'Cost Per Acquisition / Action',
        'category' => 'Marketing & Ads',
        'category_slug' => 'marketing',
        'meaning_bn' => 'Cost Per Acquisition or action',
        'description_bn' => 'Total advertising spend divided by total confirmed orders (Ad Spend ÷ Total Orders).',
        'icon' => '💳',
        'tag' => 'Cost',
    ],
    [
        'code' => 'CPM',
        'name' => 'Cost Per Mille (Per 1,000 Impressions)',
        'category' => 'Marketing & Ads',
        'category_slug' => 'marketing',
        'meaning_bn' => 'Cost Per Mille (Per 1,000 Impressions)',
        'description_bn' => 'The advertising cost charged by platforms like Meta or Google to display an ad to 1,000 user feeds.',
        'icon' => '👁️',
        'tag' => 'Impression',
    ],
    [
        'code' => 'CPC',
        'name' => 'Cost Per Click',
        'category' => 'Marketing & Ads',
        'category_slug' => 'marketing',
        'meaning_bn' => 'Cost Per Click',
        'description_bn' => 'Average advertising cost each time a prospective customer clicks on an ad to visit the store or landing page.',
        'icon' => '🖱️',
        'tag' => 'Traffic',
    ],
    [
        'code' => 'CTR',
        'name' => 'Click-Through Rate',
        'category' => 'Marketing & Ads',
        'category_slug' => 'marketing',
        'meaning_bn' => 'Click-Through Rate',
        'description_bn' => '(Total Clicks ÷ Total Impressions) × 100. Measures ad creative engagement and appeal. A 2%+ CTR is widely considered good in dropshipping.',
        'icon' => '📈',
        'tag' => 'Performance',
    ],
    [
        'code' => 'CVR',
        'name' => 'Conversion Rate',
        'category' => 'Marketing & Ads',
        'category_slug' => 'marketing',
        'meaning_bn' => 'Conversion Rate',
        'description_bn' => '(Total Orders ÷ Total Landing Page Visitors) × 100. For instance, 3 orders out of 100 visitors represents a 3% conversion rate.',
        'icon' => '🛒',
        'tag' => 'Conversion',
    ],
    [
        'code' => 'LP',
        'name' => 'Landing Page',
        'category' => 'Marketing & Ads',
        'category_slug' => 'marketing',
        'meaning_bn' => 'Dedicated product sales Landing Page',
        'description_bn' => 'Single-focus web page optimized with product details, customer reviews, and order forms where ad traffic is directed.',
        'icon' => '📄',
        'tag' => 'Web',
    ],
    [
        'code' => 'UGC',
        'name' => 'User Generated Content',
        'category' => 'Marketing & Ads',
        'category_slug' => 'marketing',
        'meaning_bn' => 'User Generated Content',
        'description_bn' => 'Customer-created unboxing videos, photos, and testimonial reviews that deliver higher trust and conversion rates in ad campaigns.',
        'icon' => '📱',
        'tag' => 'Creative',
    ],
    [
        'code' => 'CAC',
        'name' => 'Customer Acquisition Cost',
        'category' => 'Marketing & Ads',
        'category_slug' => 'marketing',
        'meaning_bn' => 'Customer Acquisition Cost',
        'description_bn' => 'Comprehensive financial cost to acquire a new paying customer, factoring in ad spend, software tools, and operational overhead.',
        'icon' => '👥',
        'tag' => 'Finance',
    ],
    [
        'code' => 'LTV',
        'name' => 'Lifetime Value (CLV)',
        'category' => 'Marketing & Ads',
        'category_slug' => 'marketing',
        'meaning_bn' => 'Customer Lifetime Value (CLV)',
        'description_bn' => 'The total cumulative revenue a customer is projected to generate for your business across their entire relationship.',
        'icon' => '💎',
        'tag' => 'Retention',
    ],

    // --- Category: SBL Network & Ecosystem ---
    [
        'code' => 'BV',
        'name' => 'Business Volume',
        'category' => 'SBL Network & System',
        'category_slug' => 'network',
        'meaning_bn' => 'Business Volume points for commission calculation',
        'description_bn' => 'Standardized point metric assigned to products and membership packages in SBL to calculate pair and matching commissions.',
        'icon' => '⚡',
        'tag' => 'Commission',
    ],
    [
        'code' => 'PV',
        'name' => 'Point Value',
        'category' => 'SBL Network & System',
        'category_slug' => 'network',
        'meaning_bn' => 'Point Value for rank advancement',
        'description_bn' => 'Numeric points attached to package enrollments used for tracking leadership rank qualifications and team milestone incentives.',
        'icon' => '⭐',
        'tag' => 'Points',
    ],
    [
        'code' => 'KYC',
        'name' => 'Know Your Customer',
        'category' => 'SBL Network & System',
        'category_slug' => 'network',
        'meaning_bn' => 'Know Your Customer identity verification',
        'description_bn' => 'Verification procedure validating national identity documents (NID) and contact numbers for member account activation.',
        'icon' => '🛡️',
        'tag' => 'Security',
    ],
    [
        'code' => 'MB',
        'name' => 'Matching Bonus',
        'category' => 'SBL Network & System',
        'category_slug' => 'network',
        'meaning_bn' => 'Matching Bonus on binary team balance',
        'description_bn' => 'Automated commission credited when sales volume points match across Left and Right binary branches.',
        'icon' => '⚖️',
        'tag' => 'Bonus',
    ],
    [
        'code' => 'GB',
        'name' => 'Generation Bonus',
        'category' => 'SBL Network & System',
        'category_slug' => 'network',
        'meaning_bn' => 'Generation Bonus across multi-tier networks',
        'description_bn' => 'Tiered commission and royalty rewards earned from active production across multi-generation referred downline networks.',
        'icon' => '🌳',
        'tag' => 'Bonus',
    ],
    [
        'code' => 'ROI',
        'name' => 'Return On Investment',
        'category' => 'SBL Network & System',
        'category_slug' => 'network',
        'meaning_bn' => 'Return On Investment',
        'description_bn' => 'Net percentage financial return earned weekly or monthly on capital invested in SBL crowdfunding or dropshipping packages.',
        'icon' => '💰',
        'tag' => 'Investment',
    ],
    [
        'code' => 'OTP',
        'name' => 'One-Time Password',
        'category' => 'SBL Network & System',
        'category_slug' => 'network',
        'meaning_bn' => 'One-Time Password security code',
        'description_bn' => 'Temporary security authentication code sent via SMS for withdrawal authorization and sensitive account actions.',
        'icon' => '🔐',
        'tag' => 'Security',
    ],

    // --- Category: Finance & Operations ---
    [
        'code' => 'COGS',
        'name' => 'Cost Of Goods Sold',
        'category' => 'Finance & Operations',
        'category_slug' => 'finance',
        'meaning_bn' => 'Cost Of Goods Sold',
        'description_bn' => 'Direct cost incurred to source or manufacture a product before advertising (Selling Price - COGS = Gross Profit).',
        'icon' => '🧾',
        'tag' => 'Accounting',
    ],
    [
        'code' => 'P&L',
        'name' => 'Profit and Loss Statement',
        'category' => 'Finance & Operations',
        'category_slug' => 'finance',
        'meaning_bn' => 'Profit and Loss financial statement',
        'description_bn' => 'Comprehensive summary of gross revenues minus COGS, ad spend, operational costs, and courier return charges to determine net profit.',
        'icon' => '📉',
        'tag' => 'Finance',
    ],
    [
        'code' => 'MFS',
        'name' => 'Mobile Financial Services',
        'category' => 'Finance & Operations',
        'category_slug' => 'finance',
        'meaning_bn' => 'Mobile Financial Services payment channel',
        'description_bn' => 'Digital wallet channels (bKash, Nagad, Rocket) used for commission payouts, customer payments, and merchant settlements.',
        'icon' => '📲',
        'tag' => 'Payment',
    ],
    [
        'code' => 'POS',
        'name' => 'Point Of Sale',
        'category' => 'Finance & Operations',
        'category_slug' => 'finance',
        'meaning_bn' => 'Point Of Sale cashier system',
        'description_bn' => 'Retail software and counter system for barcode scanning, order invoicing, and immediate transactional checkout.',
        'icon' => '🖥️',
        'tag' => 'Software',
    ],
];
